import{a as u,S as g,i as d}from"./assets/vendor-cec502ba.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const y="43840799-e71ea23b4db8ae9f9c01a8841",L="https://pixabay.com/api/";u.defaults.baseURL=L;const b=(s,t=1)=>{const o={key:y,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return u.get("?",{params:{...o}})},w=s=>`
    <a href="${s.largeImageURL}" class="item">
      <img src="${s.webformatURL}" alt="" alt="${s.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${s.likes}</span></p>
        <p><b>Views</b> <span>${s.views}</span></p>
        <p><b>Comments</b> <span>${s.comments}</span></p>
        <p><b>Downloads</b> <span>${s.downloads}</span></p>
      </div>
    </a>
  `,c=document.querySelector("form.form-search"),l=document.querySelector(".gallery"),n=document.querySelector(".loader"),a=document.querySelector(".loadMore"),v=new g(".gallery a",{});let p=1,f;const E=15,h=async(s,t=!0)=>{try{t&&(p=1,l.innerHTML="",n.classList.remove("is-hidden"));const o=await b(s,p);if(o.data.total===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"error",color:"white"}),a.classList.add("d-none"),n.classList.add("is-hidden");return}p++;const i=o.data.hits.map(e=>w(e)).join("");if(t)l.innerHTML=i;else{l.insertAdjacentHTML("beforeend",i);const{height:e}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}v.refresh(),o.data.hits.length<E?(d.info({message:"We`re sorry, but you`ve reached the end of search results.",position:"topRight",class:"info",color:"white"}),a.classList.add("d-none")):a.classList.remove("d-none")}catch(o){console.error("Error fetching images:",o),d.error({message:"Error fetching images. Please try again later.",position:"topRight",class:"error",color:"white"}),a.classList.add("d-none")}finally{n.classList.add("is-hidden")}};c&&c.addEventListener("submit",async s=>{s.preventDefault();const t=c.elements.search.value.trim();if(!t){d.error({message:"Please enter a search term",position:"topRight",class:"error",color:"white"}),a.classList.add("d-none");return}f=t,await h(t),c.reset()});a&&a.addEventListener("click",async()=>{a.classList.add("d-none"),n.classList.remove("is-hidden"),await h(f,!1),n.classList.add("is-hidden")});
//# sourceMappingURL=commonHelpers.js.map
